# Variables
@baseUrl = http://localhost:3333

# Health check
# @name healthCheck
GET {{baseUrl}}/health

###

# Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "teste",
  "description": "teste"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

###


# Get Room Question
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions


###

# Create Question
# @name createQuestion
POST {{baseUrl}}/rooms/f6aa3bb1-0556-4f49-8440-39dcd60829f1/questions
Content-Type: application/json

{
  "question": "O que é Vue.js e a sua diferenca em relacao ao Angular?"
}  